/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppCol {
        "audio": string;
        "bgColor": string;
        "height": string;
        "id": string;
        "onEntry": string;
        "onMatch": string;
        "onTouch": string;
        "type": string;
        "value": string;
        "visible": boolean;
        "width": string;
        "x": string;
        "y": string;
        "z": string;
    }
    interface AppContainer {
        "audio": string;
        "bgColor": string;
        "height": string;
        "onEntry": string;
        "onMatch": string;
        "onTouch": string;
        "type": string;
        "value": string;
        "visible": boolean;
        "width": string;
        "x": string;
        "y": string;
        "z": string;
    }
    interface AppHome {
        "xmlData": string;
    }
    interface AppImage {
        "audio": string;
        "bgColor": string;
        "height": string;
        "onEntry": string;
        "onMatch": string;
        "onTouch": string;
        "src": string;
        "type": string;
        "value": string;
        "visible": boolean;
        "width": string;
        "x": string;
        "y": string;
        "z": string;
    }
    interface AppObjective {
        "string": string;
        "value": string;
    }
    interface AppPos {
        "audio": string;
        "bgColor": string;
        "height": string;
        "id": string;
        "onEntry": string;
        "onMatch": string;
        "onTouch": string;
        "type": string;
        "value": string;
        "visible": boolean;
        "width": string;
        "x": string;
        "y": string;
        "z": string;
    }
    interface AppRandom {
        "audio": string;
        "bgColor": string;
        "height": string;
        "id": string;
        "onEntry": string;
        "onMatch": string;
        "onTouch": string;
        "type": string;
        "value": string;
        "visible": boolean;
        "width": string;
        "x": string;
        "y": string;
        "z": string;
    }
    interface AppRoot {
    }
    interface AppRow {
        "audio": string;
        "bgColor": string;
        "height": string;
        "onEntry": string;
        "onMatch": string;
        "onTouch": string;
        "type": string;
        "value": string;
        "visible": boolean;
        "width": string;
        "x": string;
        "y": string;
        "z": string;
    }
    interface AppShape {
        "audio": string;
        "bgColor": string;
        "height": string;
        "id": string;
        "onEntry": string;
        "onMatch": string;
        "onTouch": string;
        "shapeType": string;
        "type": string;
        "value": string;
        "visible": boolean;
        "width": string;
        "x": string;
        "y": string;
        "z": string;
    }
    interface AppText {
        "audio": string;
        "bgColor": string;
        "font": string;
        "fontSize": string;
        "height": string;
        "highlightWhileSpeaking": boolean;
        "id": string;
        "onEntry": string;
        "onMatch": string;
        "onTouch": string;
        "string": string;
        "type": string;
        "value": string;
        "visible": boolean;
        "width": string;
        "x": string;
        "y": string;
        "z": string;
    }
    interface AppWrap {
        "audio": string;
        "bgColor": string;
        "height": string;
        "id": string;
        "onEntry": string;
        "onMatch": string;
        "onTouch": string;
        "type": string;
        "value": string;
        "visible": boolean;
        "width": string;
        "x": string;
        "y": string;
        "z": string;
    }
}
declare global {
    interface HTMLAppColElement extends Components.AppCol, HTMLStencilElement {
    }
    var HTMLAppColElement: {
        prototype: HTMLAppColElement;
        new (): HTMLAppColElement;
    };
    interface HTMLAppContainerElement extends Components.AppContainer, HTMLStencilElement {
    }
    var HTMLAppContainerElement: {
        prototype: HTMLAppContainerElement;
        new (): HTMLAppContainerElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppImageElement extends Components.AppImage, HTMLStencilElement {
    }
    var HTMLAppImageElement: {
        prototype: HTMLAppImageElement;
        new (): HTMLAppImageElement;
    };
    interface HTMLAppObjectiveElement extends Components.AppObjective, HTMLStencilElement {
    }
    var HTMLAppObjectiveElement: {
        prototype: HTMLAppObjectiveElement;
        new (): HTMLAppObjectiveElement;
    };
    interface HTMLAppPosElement extends Components.AppPos, HTMLStencilElement {
    }
    var HTMLAppPosElement: {
        prototype: HTMLAppPosElement;
        new (): HTMLAppPosElement;
    };
    interface HTMLAppRandomElement extends Components.AppRandom, HTMLStencilElement {
    }
    var HTMLAppRandomElement: {
        prototype: HTMLAppRandomElement;
        new (): HTMLAppRandomElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppRowElement extends Components.AppRow, HTMLStencilElement {
    }
    var HTMLAppRowElement: {
        prototype: HTMLAppRowElement;
        new (): HTMLAppRowElement;
    };
    interface HTMLAppShapeElement extends Components.AppShape, HTMLStencilElement {
    }
    var HTMLAppShapeElement: {
        prototype: HTMLAppShapeElement;
        new (): HTMLAppShapeElement;
    };
    interface HTMLAppTextElement extends Components.AppText, HTMLStencilElement {
    }
    var HTMLAppTextElement: {
        prototype: HTMLAppTextElement;
        new (): HTMLAppTextElement;
    };
    interface HTMLAppWrapElement extends Components.AppWrap, HTMLStencilElement {
    }
    var HTMLAppWrapElement: {
        prototype: HTMLAppWrapElement;
        new (): HTMLAppWrapElement;
    };
    interface HTMLElementTagNameMap {
        "app-col": HTMLAppColElement;
        "app-container": HTMLAppContainerElement;
        "app-home": HTMLAppHomeElement;
        "app-image": HTMLAppImageElement;
        "app-objective": HTMLAppObjectiveElement;
        "app-pos": HTMLAppPosElement;
        "app-random": HTMLAppRandomElement;
        "app-root": HTMLAppRootElement;
        "app-row": HTMLAppRowElement;
        "app-shape": HTMLAppShapeElement;
        "app-text": HTMLAppTextElement;
        "app-wrap": HTMLAppWrapElement;
    }
}
declare namespace LocalJSX {
    interface AppCol {
        "audio"?: string;
        "bgColor"?: string;
        "height"?: string;
        "id"?: string;
        "onEntry"?: string;
        "onMatch"?: string;
        "onTouch"?: string;
        "type"?: string;
        "value"?: string;
        "visible"?: boolean;
        "width"?: string;
        "x"?: string;
        "y"?: string;
        "z"?: string;
    }
    interface AppContainer {
        "audio"?: string;
        "bgColor"?: string;
        "height"?: string;
        "onEntry"?: string;
        "onMatch"?: string;
        "onTouch"?: string;
        "type"?: string;
        "value"?: string;
        "visible"?: boolean;
        "width"?: string;
        "x"?: string;
        "y"?: string;
        "z"?: string;
    }
    interface AppHome {
        "xmlData"?: string;
    }
    interface AppImage {
        "audio"?: string;
        "bgColor"?: string;
        "height"?: string;
        "onEntry"?: string;
        "onMatch"?: string;
        "onTouch"?: string;
        "src"?: string;
        "type"?: string;
        "value"?: string;
        "visible"?: boolean;
        "width"?: string;
        "x"?: string;
        "y"?: string;
        "z"?: string;
    }
    interface AppObjective {
        "string"?: string;
        "value"?: string;
    }
    interface AppPos {
        "audio"?: string;
        "bgColor"?: string;
        "height"?: string;
        "id"?: string;
        "onEntry"?: string;
        "onMatch"?: string;
        "onTouch"?: string;
        "type"?: string;
        "value"?: string;
        "visible"?: boolean;
        "width"?: string;
        "x"?: string;
        "y"?: string;
        "z"?: string;
    }
    interface AppRandom {
        "audio"?: string;
        "bgColor"?: string;
        "height"?: string;
        "id"?: string;
        "onEntry"?: string;
        "onMatch"?: string;
        "onTouch"?: string;
        "type"?: string;
        "value"?: string;
        "visible"?: boolean;
        "width"?: string;
        "x"?: string;
        "y"?: string;
        "z"?: string;
    }
    interface AppRoot {
    }
    interface AppRow {
        "audio"?: string;
        "bgColor"?: string;
        "height"?: string;
        "onEntry"?: string;
        "onMatch"?: string;
        "onTouch"?: string;
        "type"?: string;
        "value"?: string;
        "visible"?: boolean;
        "width"?: string;
        "x"?: string;
        "y"?: string;
        "z"?: string;
    }
    interface AppShape {
        "audio"?: string;
        "bgColor"?: string;
        "height"?: string;
        "id"?: string;
        "onEntry"?: string;
        "onMatch"?: string;
        "onTouch"?: string;
        "shapeType"?: string;
        "type"?: string;
        "value"?: string;
        "visible"?: boolean;
        "width"?: string;
        "x"?: string;
        "y"?: string;
        "z"?: string;
    }
    interface AppText {
        "audio"?: string;
        "bgColor"?: string;
        "font"?: string;
        "fontSize"?: string;
        "height"?: string;
        "highlightWhileSpeaking"?: boolean;
        "id"?: string;
        "onEntry"?: string;
        "onMatch"?: string;
        "onTouch"?: string;
        "string"?: string;
        "type"?: string;
        "value"?: string;
        "visible"?: boolean;
        "width"?: string;
        "x"?: string;
        "y"?: string;
        "z"?: string;
    }
    interface AppWrap {
        "audio"?: string;
        "bgColor"?: string;
        "height"?: string;
        "id"?: string;
        "onEntry"?: string;
        "onMatch"?: string;
        "onTouch"?: string;
        "type"?: string;
        "value"?: string;
        "visible"?: boolean;
        "width"?: string;
        "x"?: string;
        "y"?: string;
        "z"?: string;
    }
    interface IntrinsicElements {
        "app-col": AppCol;
        "app-container": AppContainer;
        "app-home": AppHome;
        "app-image": AppImage;
        "app-objective": AppObjective;
        "app-pos": AppPos;
        "app-random": AppRandom;
        "app-root": AppRoot;
        "app-row": AppRow;
        "app-shape": AppShape;
        "app-text": AppText;
        "app-wrap": AppWrap;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-col": LocalJSX.AppCol & JSXBase.HTMLAttributes<HTMLAppColElement>;
            "app-container": LocalJSX.AppContainer & JSXBase.HTMLAttributes<HTMLAppContainerElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-image": LocalJSX.AppImage & JSXBase.HTMLAttributes<HTMLAppImageElement>;
            "app-objective": LocalJSX.AppObjective & JSXBase.HTMLAttributes<HTMLAppObjectiveElement>;
            "app-pos": LocalJSX.AppPos & JSXBase.HTMLAttributes<HTMLAppPosElement>;
            "app-random": LocalJSX.AppRandom & JSXBase.HTMLAttributes<HTMLAppRandomElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-row": LocalJSX.AppRow & JSXBase.HTMLAttributes<HTMLAppRowElement>;
            "app-shape": LocalJSX.AppShape & JSXBase.HTMLAttributes<HTMLAppShapeElement>;
            "app-text": LocalJSX.AppText & JSXBase.HTMLAttributes<HTMLAppTextElement>;
            "app-wrap": LocalJSX.AppWrap & JSXBase.HTMLAttributes<HTMLAppWrapElement>;
        }
    }
}
