name: Dev Build

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install app dependencies
        run: npm install

      - name: Build
        env:
          CI: false
        run: npm run build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13.0.3
        with:
          args: deploy --only hosting:lido-player-dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}